### ISSUE TITLE
Request-URI Too Large - Logging in with Google

### ISSUE THREAD

**Issue by stevecastaneda** [markusproske/omniauth_pure#1]
Clone repository, installed gems and migrated database. Started Webrick and attempted to login with Google. The callback URL looks like it's too large.  The data is being passed as parameters to the callback URL for some reason.

Ruby 1.9.2-p0, using Rails 3.0.5 per gemfile specs

`[2011-05-06 16:46:41] ERROR WEBrick::HTTPStatus::RequestURITooLarge
[2011-05-06 16:46:41] ERROR TypeError: can't convert nil into an exact number
/Users/realestatesteve/.rvm/gems/ruby-1.9.2-p0@rails3tutorial/gems/activesupport-3.0.5/lib/active_support/core_ext/time/calculations.rb:257:in `-'
/Users/realestatesteve/.rvm/gems/ruby-1.9.2-p0@rails3tutorial/gems/activesupport-3.0.5/lib/active_support/core_ext/time/calculations.rb:257:in `minus_with_duration'
/Users/realestatesteve/.rvm/gems/ruby-1.9.2-p0@rails3tutorial/gems/activesupport-3.0.5/lib/active_support/core_ext/time/calculations.rb:268:in `minus_with_coercion'
/Users/realestatesteve/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/accesslog.rb:42:in `setup_params'
/Users/realestatesteve/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:164:in `access_log'
/Users/realestatesteve/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/httpserver.rb:87:in `run'
/Users/realestatesteve/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'`

**Comment by markusproske** [comment]
This seems to be an issue of Webrick, not Omniauth (or my Omniauth pure). A solution could be to switch to mongrel, see here: https://github.com/intridea/omniauth/issues/43.
