### ISSUE TITLE
communityguides.eu is no more

### ISSUE THREAD

**Issue by anoopprasad** [markusproske/omniauth_pure#11]
Can you please tell me why the site is down. I am not able to find any articles nor site

**Comment by azurewraith** [comment]
I saw it up last night, but today I'm not able to access it.  Must be going up and down?

**Comment by markusproske** [comment]
Domain expired, the content is still on Heroku: http://communityguides.heroku.com/

**Comment by azurewraith** [comment]
I noticed that a little later, thanks for updating the README.  You might want to edit the projects tagline too which still has a reference to the old domain.

**Comment by anoopprasad** [comment]
Thanks for the update :)

**Comment by anoopprasad** [comment]
Communityguide heroku app is also down.. Do you hosted it some where ?
