### ISSUE TITLE
Extending out the services for token and secret

### ISSUE THREAD

**Issue by macboyrules** [markusproske/omniauth_pure#2]
Hi Markus, this is a great starting point for creating an omniauth authentication scheme without any other parts like Devise.  Great work :)

I am stuck trying to extend out the services to include tokens and secrets.  Here is the code I added to the services controller:

In def newaccount:

<code>@newuser.services.build(:provider => session[:authhash][:provider], :uid => session[:authhash][:uid], :uname => session[:authhash][:name], :uemail => session[:authhash][:email], :token => session[:authhash][:token], :secret => session[:authhash][:secret])</code>

and in def create, service route facebook:

<code>omniauth['provider'] ? @authhash[:provider] = omniauth['provider'] : @authhash[:provider] = ''
omniauth['credentials']['token'] ? @authhash[:token] = omniauth['credentials']['token'] : @authhash[:token] = ''
omniauth['credentials']['secret'] ? @authhash[:secret] = omniauth['credentials']['secret'] : @authhash[:secret] = ''</code>

The problem I have is that it is returning nil, even though according to the omniauth wiki, I am using the right omniauth calls.  I did extent out the schema, and I don't get an error when the program runs, it just returns nil.

I want to populate these in the services database so that I can retrieve them later without querying the session, possibly using them off-line.

Any suggestions?

Thanks.

**Comment by markusproske** [comment]
Did you add your new fields to `attr_accessible :provider, :uid, :uname, :uemail`? Otherwise, the mass assignment will skip these values (and you'll see a message in your Terminal where the server runs). 

Second, if you output token and secret with Rails.logger, do they contain data or are you writing nil do the services db?

**Comment by macboyrules** [comment]
Markus,

  Ok, thanks.  I found my problem(s).

  First, I forgot that Facebook is Oauth2, so it doesn't pass secret, because it doesn't need it. *slap

  Second, I found that I had put the secret and token in the create when the users was first created, but not in the "add another service" section.  Fixed that, and voila!

  Thanks for your prompt response.
