### ISSUE TITLE
don't lock the user in

### ISSUE THREAD

**Issue by pawel2105** [markusproske/omniauth_pure#7]
In your session controller IIRC, you have:

```
if session[:service_id] == @service.id
  flash[:error] = 'You are currently signed in with this account!'
else
  @service.destroy
end
```

You may want to edit this so that if a user has removed all of his other services, he is also able to remove this last one. Try something like,

```
if session[:service_id] == @service.id && current_user.services > 1
  flash[:error] = 'You are currently signed in with this account. Please sign in with one of your other accounts to remove this one.'
else
  @service.destroy
end
```

**Comment by markusproske** [comment]
Well, one could do that. However, there are situations, where you do not want your user to leave as fast, there might be some clean-up todo (e.g. think of public comments by the users) or you might want to send an email to receive a confirmation. Therefore the demo code does not allow to remove the last service and you have to write your own routines to remove a user (or modify the code as you proposed).
