### ISSUE TITLE
Can't find route for auths

### ISSUE THREAD

**Issue by fermuch** [markusproske/omniauth_pure#8]
When I follow the links to go to login in facebook, I get the following message:

> Routing Error
> No route matches [GET] "/auth/facebook"
> Try running rake routes for more information on available routes.

I don't know what I'm doing wrong. Please, tell me if you need more data.

**Comment by fermuch** [comment]
Oh, snap! I forgot to copy the contents of the environment! Please, add it to the readme!

**Comment by adamwong246** [comment]
Same problem, this fixed it. Indeed, add to this to the readme. Also, add to step reminding the user to copy over the needed gem from the gemfile.
